class CFirebase {
  CFirebase._();
  static const String users = 'users';
  static const String role = 'role';
  static const String customer = 'customer';
  static const String admin = 'admin';
  static const String name = 'name';
  static const String email = 'email';
  static const String imageUrl = 'imageUrl';
  static const String uid = 'uid';
  static const String addresses = 'addresses';

  static const String product = 'product';
  static const String cartDetails = 'cartDetails';
  static const String products = 'products';
  static const String id = 'id';
  static const String thumbnail = 'thumbnail';
  static const String otherImages = 'otherImages';
  static const String category = 'category';
  static const String brand = 'brand';
  static const String sizes = 'sizes';
  static const String details = 'details';
  static const String soleType = 'soleType';
  static const String outerType = 'outerType';
  static const String closure = 'closure';
  static const String gender = 'gender';
  static const String weight= 'weight';
  static const String isWaterResistant = 'isWaterResistant';
  static const String isBreathable = 'isBreathable';
  static const String stock = 'stock';
  static const String available = 'available';
  static const String quantity = 'quantity';
  static const String purchaseHistory = 'purchaseHistory';
  static const String price = 'price';
  static const String ratings = 'ratings';
  static const String avg = 'avg';
  static const String reviews = 'reviews';
  static const String profile = 'profile';
  static const String comment = 'comment';
  static const String rating = 'rating';
  static const String postedAt = 'postedAt';

  static const String banners = 'banners';
  static const String cart = 'cart';
  static const String inr = 'INR';
  static const String usd = 'USD';
  static const String eur = 'EUR';
  static const String gbp = 'GBP';
  static const String productId = 'productId';
  static const String size = 'size';
  static const String image = 'image';
  static const String tagline = 'tagline';
  static const String logo = 'logo';
  static const String amount = 'amount';
  static const String symbol = 'symbol';
  static const String code = 'code';
}