name: together_travel
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  cloud_firestore: ^5.5.0
  firebase_auth: ^5.3.3
  firebase_core: ^3.8.0
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.9.3
  get: ^4.6.6
  shared_preferences: ^2.3.3
  flutter_native_splash: ^2.4.3
  smooth_page_indicator: ^1.2.0+3
  image_picker: ^1.1.2
  firebase_storage: ^12.3.6
  google_maps_flutter: ^2.10.0
  google_places_flutter: ^2.0.9
  http: ^1.2.2
  flutter_svg: ^2.0.16
#  razorpay_flutter: ^1.3.7
  intl: ^0.20.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: Quicksand
      fonts:
        - asset: assets/fonts/Quicksand-Light.ttf
          weight: 300
        - asset: assets/fonts/Quicksand-Regular.ttf
          weight: 400
        - asset: assets/fonts/Quicksand-Medium.ttf
          weight: 500
        - asset: assets/fonts/Quicksand-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Quicksand-Bold.ttf
          weight: 700
          
  assets: 
    - assets/images/
    - assets/icons/
